blank_issues_enabled: false

contact_links:
  - name: Security vulnerability
    url: https://github.com/chyVacheck/PocketFiles/security/policy
    about: Report security vulnerabilities privately using the security policy.
